package it.polimi.ingsw.network;

public enum MessageType {
    GAME_STARTED,
    LOBBY_FULL,
    DROP_LEADER_CARD,
    PLAY_LEADER_CARD,
    BUY_DEVELOPMENT_CARD,
    PICK_RESOURCES,
    START_PRODUCTION,
    END_TURN,
    ACTION_SUCCESS,
    EXCEPTION_MESSAGE,
    USERNAME_MESSAGE,
    CREATE_OR_JOIN_LOBBY,
    SPECIFY_LOBBY_DIM
}
